# Generated by Django 4.0.2 on 2022-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0002_donation_is_taken_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='more_info',
            field=models.TextField(null=True),
        ),
    ]
